# Generated by Django 5.0.4 on 2024-05-23 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_question_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
